# Generated by Django 3.2.7 on 2021-10-27 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
